#!/bin/sh
# Example script ... Customize it!
# Add as a function
# Do not touch the function name
app() {
#Add a warning if using a module manager (etc, gem, pip,npm)
#echo "Warning: If <module manager> is not installed please install it"
echo "Starting.."
#sleep <any value> (must be bellow 10)
echo "Making files.."
mkdir $*
cd $*
mkdir src
echo "
 add starter code here
" > src/$*.something
# You can make it initalize a git repo
#git init
echo "Done"
exit 10
}
app $*
# Dont change this
